image: golang:1.16

pipelines:
  custom:
    test:
      - parallel:
        - step:
            name: Test and Build
            script:
              - mkdir -p test-reports
              - go get -u github.com/jstemmer/go-junit-report
              - go test ./... -v 2>&1 | go-junit-report > test-reports/report.xml
              # Build compiles the packages
              - go build -v jira-timespent-report.go
        - step:
            name: Lint code
            image: golangci/golangci-lint:v1.31.0
            script:
              - mkdir -p test-reports
              - golangci-lint run -v --skip-files jira/version.go --out-format junit-xml --issues-exit-code 0 > test-reports/lint.xml
